tap 'anomalyco/tap'
brew 'zsh'
brew 'gh'
brew 'fnm'
brew 'mole'
brew 'opencode'
brew 'stow'
brew 'lazygit'

tap 'homebrew/cask-fonts'
cask 'font-jetbrains-mono'
cask 'iterm2'
cask 'raycast'
cask 'visual-studio-code'
cask 'zed'
cask 'bitwarden'
cask 'github'
cask 'karabiner-elements'
